# Generated by Django 2.0.7 on 2018-07-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='produto',
            field=models.ManyToManyField(blank=True, to='clientes.Produto'),
        ),
    ]
