version: '3'

services:
  nodejs:
    image: node
    working_dir: /home/src
    volumes:
      - .:/home/src
    command: bash
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
      - 3003:3003
    user: node